#!/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# docker rm -f debian-zabbix

docker run -d --name debian-zabbix \
    --privileged \
    --net host \
    -v /sys/fs/cgroup:/sys/fs/cgroup \
    -v $SCRIPT_DIR/../../common/bin/:/usr/local/bin \
    robertdebock/debian:bookworm
