#!/bin/env bash

apt-get update -qq
apt-get install -yqq \
    zabbix-agent \
    zabbix-server-mysql \
    zabbix-frontend-php

cat << EOF > /etc/apache2/conf-available/zabbix.conf
<IfModule mod_alias.c>
    Alias /zabbix /usr/share/zabbix
</IfModule>

# Définition des droits d'accès au dossier contenant les fichiers web de zabbix
<Directory /usr/share/zabbix>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Order allow,deny
        allow from all
</Directory>
EOF

cat << EOF > /etc/apache2/sites-available/zabbix.conf
<VirtualHost *:80> 
      ServerAdmin webmaster@localhost 
      DocumentRoot /usr/share/zabbix/ 
         <Directory /> 
              Options FollowSymLinks 
              AllowOverride None 
      </Directory> 
      <Directory /usr/share/zabbix/> 
              Options Indexes FollowSymLinks MultiViews 
              AllowOverride None 
              Order allow,deny 
              allow from all 
      </Directory> 
      <Directory /usr/share/zabbix/> 
              Options Indexes FollowSymLinks MultiViews 
              AllowOverride None 
              Order allow,deny 
              allow from all 
      </Directory>
       ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/ 
      <Directory "/usr/lib/cgi-bin"> 
              AllowOverride None 
              Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch 
              Order allow,deny 
              Allow from all 
      </Directory> 
      ErrorLog \${APACHE_LOG_DIR}/error.log 
      # Possible values include: debug, info, notice, warn, error, crit, 
      # alert, emerg. 
      LogLevel warn
      CustomLog \${APACHE_LOG_DIR}/access.log combined 
</VirtualHost>  
EOF

a2enconf zabbix
a2ensite zabbix
a2dissite 000-default.conf

systemctl restart apache2.service
