services:

  db:
    image: mariadb
    restart: unless-stopped
    # ports:
    #   - 3306:3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}

  zabbix:
    image: zabbix/zabbix-server-mysql:ubuntu-latest
    # ports:
    #   - 10051:10051
    restart: unless-stopped
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    environment:
      DB_SERVER_HOST: db
      DB_SERVER_PORT: 3306
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DB: ${DB_NAME}
    depends_on:
      - db

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      DB_SERVER_HOST: db
      DB_SERVER_PORT: 3306
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DB: ${DB_NAME}
      PHP_TZ: ${TZ}
      ZBX_SERVER_HOST: zabbix
      ZBX_SERVER_PORT: 10051
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      - zabbix

  zabbix-agent:
    image:  zabbix/zabbix-agent:ubuntu-latest
    restart: unless-stopped
    # ports:
    #   - "10050:10050"
    environment:
      ZBX_ACTIVE_ALLOW: false
      TZ: ${TZ}
      ZBX_SERVER_HOST: zabbix
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: zabbix-agent
      ZBX_HOSTNAMEITEM: system.hostname
    depends_on:
      - zabbix
